name: frontend_aplication
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
  google_fonts: ^6.2.1
  country_picker: ^2.0.27
  english_words: ^4.0.0
  provider: ^6.0.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  http: ^1.2.2
  file_picker: ^8.1.7
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.1
  mime: ^2.0.0
  http_parser: ^4.0.2
  shared_preferences: ^2.5.1
  flutter_animate: ^4.2.0
  awesome_dialog: ^3.2.1
  animated_button: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  http_mock_adapter: ^0.6.1
  build_runner: ^2.1.5

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/breeds/
    - assets/data/