name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Paso 1: Hacer checkout del repositorio
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Paso 2: Configurar Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0' # Puedes especificar una versión específica si lo necesitas.

      # Paso 3: Instalar dependencias de Flutter
      - name: Install dependencies
        run: flutter pub get

      # Paso 4: Ejecutar la compilación para la web
      - name: Build Flutter Web
        run: flutter build web

      # Paso 5: Desplegar la aplicación a Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_DUNE_0183CA803 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"  # Ubicación de tu código fuente (asegúrate que sea correcto)
          api_location: ""   # Si no tienes Azure Functions, esto está vacío
          output_location: "build/web"  # Aquí están los archivos generados por Flutter

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_DUNE_0183CA803 }}
          action: "close"
